name: Build

on: 
  push:
    branches:
      - 'master'
  pull_request:


jobs:
  quality:
    runs-on: ubuntu-20.04
    matrix:
      ARCH: ['x86_64', 'i386']
      COVERAGE: ['On', 'Off']
      DESKTOP_UTILS_ENABLED: [true, false]
      docker-image: ['appimagebuild', 'appimagebuild-i386']
      
      exclude: 
        x86_64: 'appimagebuild-i386'
        i386: 'appimagebuild'
    env:
      ARCH: ${{ matrix.ARCH }}
      ENABLE_COVERAGE: ${{ matrix.COVERAGE }}

    container: 
      image: quay.io/appimage/${{ matrix.docker-image }}
      options: "--cap-add SYS_ADMIN --device /dev/fuse:mrw"

    steps:
    - uses: actions/checkout@v2

    - name: Install deps (libfuse-dev, desktop-file-utils) (${{ matrix.ARCH }})
      if: matrix.DESKTOP_UTILS_ENABLED == true
      run: |
        sudo apt-get -y install libfuse-dev desktop-file-utils

    - name: Install deps (gcovr, lcov) (${{ matrix.ARCH }})
      if: matrix.COVERAGE == 'On'
      run: |
        sudo apt-get -y install gcovr lcov

    - name: Test (${{ matrix.ARCH }})
      run: |
        cd libappimage
        bash -ex ../travis/build-and-test.sh

